### ISSUE TITLE
A question regarding BBO

### ISSUE THREAD

**Issue by Alex1os** [Step7750/BetterBuyOrders#1]
Hello Sir,

I just wanted to say I love your work. The extension works great and I am very happy to see more buy orders now.

My question is:

Is it possible to somehow see which of the buy orders are which real currency? I took a look at the code with the chrome console but I cannot seem to find the currencies of he lets say top five in the list.

regards

Alex

**Comment by Step7750** [comment]
As far as I know, the buy orders are converted on-demand to the currency of your choice. I don't know the exact conversion rates that Valve uses nor is there a public API for accessing this data (AFAIK).
