### ISSUE TITLE
Buy Orders on Unlisted Market Items

### ISSUE THREAD

**Issue by Vampurica** [Step7750/BetterBuyOrders#2]
Can't seem to place buy orders on items that are unlisted.
Returns: "There was a problem purchasing your item. The listing may have been removed. Refresh the page and try again."

Not sure if steam updated something or not.

**Comment by Vampurica** [comment]
Found that this is true for items that were never sold on the steam market before. If there is a sale history the buy order will work.

**Comment by Step7750** [comment]
Yeah, if the item has never been sold on the market before, the buy order system doesn't work correctly. No worries!
