### ISSUE TITLE
Extension Causing 403 Forbidden/Access Denied Errors

### ISSUE THREAD

**Issue by Bonsai99** [Step7750/BetterBuyOrders#6]
Only happens when using the extension after a period of ~15 minutes.
https://i.imgur.com/MGg64Wp.png

I think this might be caused by sending too many requests.

Here is what the normal amount of requests made on a market page looks like compared to when using the extension:
[Normal](https://i.imgur.com/oeLKwKu.png)
[With Extension](https://i.imgur.com/H20kWLh.png)

**Comment by Step7750** [comment]
Let me know if you have any other issues, it'll take some time for the changes to propagate.
